// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNVoFZ2JmxgLQSO54WWtDcvv0cZxIFPJ4',
    appId: '1:710620080875:web:4b71ba5a9db772974a6cae',
    messagingSenderId: '710620080875',
    projectId: 'seestyledb',
    authDomain: 'seestyledb.firebaseapp.com',
    storageBucket: 'seestyledb.firebasestorage.app',
    measurementId: 'G-43ZB0VE3GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JTJcUx5gtiaei2lYJHSkTMFP2JPE84I',
    appId: '1:710620080875:android:1860ba1721bed6b84a6cae',
    messagingSenderId: '710620080875',
    projectId: 'seestyledb',
    storageBucket: 'seestyledb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZgCHYPvoPUfRngDVvzjTl4byHN1MR2qI',
    appId: '1:710620080875:ios:b975e6a841f75b004a6cae',
    messagingSenderId: '710620080875',
    projectId: 'seestyledb',
    storageBucket: 'seestyledb.firebasestorage.app',
    iosBundleId: 'com.example.seestyleFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZgCHYPvoPUfRngDVvzjTl4byHN1MR2qI',
    appId: '1:710620080875:ios:b975e6a841f75b004a6cae',
    messagingSenderId: '710620080875',
    projectId: 'seestyledb',
    storageBucket: 'seestyledb.firebasestorage.app',
    iosBundleId: 'com.example.seestyleFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNVoFZ2JmxgLQSO54WWtDcvv0cZxIFPJ4',
    appId: '1:710620080875:web:3ee3a1931dbcc5f44a6cae',
    messagingSenderId: '710620080875',
    projectId: 'seestyledb',
    authDomain: 'seestyledb.firebaseapp.com',
    storageBucket: 'seestyledb.firebasestorage.app',
    measurementId: 'G-EWS633ME9T',
  );
}
